kind = "web"
previewPath = "/"
title = "Jinambe Technologies"
version = "1.0.0"
id = "artifacts/jinambe"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20637

[services.development]
run = "pnpm --filter @workspace/jinambe run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jinambe", "run", "build" ]
publicDir = "artifacts/jinambe/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20637"
BASE_PATH = "/"
